# Generated by Django 2.2.2 on 2019-06-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='tweetuser',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_mentions',
            field=models.ManyToManyField(to='warehouse.TweetUser'),
        ),
    ]
