# Generated by Django 2.2.2 on 2019-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190629_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='hash_tags',
            field=models.ManyToManyField(to='warehouse.HashTag'),
        ),
    ]
