# Generated by Django 2.2.2 on 2019-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20190629_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'default_related_name': 'tweets', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hash_tags',
            field=models.ManyToManyField(related_name='tweets', to='warehouse.HashTag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_mentions',
            field=models.ManyToManyField(related_name='tweets', to='warehouse.TweetUser'),
        ),
    ]
