# Generated by Django 2.2.2 on 2019-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20190629_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, related_name='tweets', to='warehouse.HashTag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_mentions',
            field=models.ManyToManyField(blank=True, related_name='tweets', to='warehouse.TweetUser'),
        ),
    ]
