# Generated by Django 2.2.2 on 2019-07-01 21:08

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_tweet_retweet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
