# Generated by Django 2.2.2 on 2019-07-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_tweet_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'default_related_name': 'tweets', 'ordering': ('-favorite_count',)},
        ),
    ]
