# Generated by Django 2.2.2 on 2019-07-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20190702_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tip',
            field=models.CharField(max_length=140),
        ),
    ]
